#import "../template.typ": *

= Part XIX. Glossary <part-xix-glossary>

#table(
  columns: (2.1fr, 6.4fr),
  table.header([Term], [Definition]),
  [ADC], [analogue to digital converter: turns a voltage into a number],
  [ADS], [Keysight Advanced Design System, a circuit and system RF simulator],
  [AEDT], [Ansys Electronics Desktop, the environment that hosts HFSS],
  [AP-S], [IEEE Antennas and Propagation Society],
  [array factor], [the coherent sum of element contributions for given weights, as a function of direction],
  [array state $vb(H)_t$], [the complex errors that turn commanded weights into realised weights at time $t$],
  [attenuation constant $alpha$], [rate of amplitude decay along a line, Np/m or dB/m],
  [beamforming], [combining element signals with weights to form a directional pattern],
  [beamwidth, half power], [the angle between the two directions where the beam is 3 dB below its peak],
  [Bayesian experimental design], [choosing measurements to maximise expected information about unknowns],
  [Bayesian optimisation], [searching for the input that maximises an expensive function, with a probabilistic surrogate],
  [broadside], [the direction normal to the array],
  [calibration], [estimating the array state so that commands can be corrected],
  [common mode error], [an error identical on all channels; unobservable in beam shape],
  [coupling, mutual], [the influence of one element or channel on another],
  [coupon], [a test structure fabricated beside a circuit to characterise the board],
  [dB], [ten times the base 10 logarithm of a power ratio, or twenty times that of an amplitude ratio],
  [dBi], [antenna gain relative to an isotropic radiator],
  [dBm], [power relative to 1 mW in decibels],
  [DE1-SoC], [Terasic board with an Intel Cyclone V system on chip: FPGA fabric plus an ARM processor],
  [de-embedding], [mathematically removing a characterised fixture from a measurement],
  [directivity], [radiation intensity in a direction relative to its average over all directions],
  [drift], [slow change of the array state over time],
  [effective permittivity $epsilon_"eff"$], [the permittivity of a uniform medium that would give a microstrip's propagation constant],
  [embedded element pattern], [the pattern of one element excited inside the array, the others terminated],
  [enable switch], [the per channel switch that passes the signal or terminates the channel in 50 ohm],
  [ENIG], [electroless nickel immersion gold, a surface finish],
  [ERC], [electrical rule check of a schematic],
  [far field], [the region where the pattern no longer depends on distance; beyond about $2 D^2 \/ lambda$],
  [FPGA], [field programmable gate array: configurable digital logic with deterministic timing],
  [FR-4], [glass reinforced epoxy laminate, the standard PCB material],
  [G1 to G5], [the project's gates: phase measurability, drift above floor, element and bit count, coupling adequacy, budget],
  [Gaussian process (GP)], [a probability distribution over functions, defined by a mean and a covariance kernel],
  [grating lobe], [an unwanted full strength lobe caused by spacing that is too large],
  [guided wavelength $lambda_g$], [the wavelength inside a transmission line, $lambda_0 \/ sqrt(epsilon_"eff")$],
  [HFSS], [Ansys High Frequency Structure Simulator, a finite element full wave solver],
  [HPS], [hard processor system: the ARM processor inside the Cyclone V SoC],
  [identifiability], [whether parameters can in principle be determined from the available measurements],
  [illuminator of opportunity], [a transmitter operating for its own purpose whose field a separate receiver uses for sensing],
  [insertion loss], [the loss a component adds in a matched system, $- 20 log_10 abs(S_21)$],
  [ISAC], [integrated sensing and communication: systems sharing spectrum, waveform, hardware, aperture or field between communication and sensing; three families in section 10bis.2],
  [isolation], [attenuation of a switch between its common port and its off throw],
  [Kalman filter], [the recursive Bayesian estimator for linear Gaussian state space models],
  [likelihood], [probability of the observed data given the parameters; here, the physical forward model],
  [microstrip], [a strip conductor over a grounded dielectric],
  [multipath], [the arrival of one transmitter's signal at the receiver by several propagation paths],
  [passive bistatic radar], [sensing with a receiver separated from a transmitter it does not control],
  [MTT-S], [IEEE Microwave Theory and Technology Society],
  [null], [a direction of near total cancellation in a pattern],
  [PE4259-63], [the pSemi SPDT RF switch used throughout Rev A],
  [phase constant $beta$], [phase accumulated per unit length, rad/m],
  [phase retrieval], [recovering a complex vector from magnitude measurements],
  [phase shifter], [a device that changes the phase of a signal; here, three switched line bits per channel],
  [phasor], [a complex number representing the amplitude and phase of a sinusoid],
  [posterior], [the probability distribution of the parameters after the data],
  [prior], [the probability distribution of the parameters before the new data],
  [quantisation], [rounding a continuous command to the nearest reachable state],
  [quiet window], [the interval from strobe to end of conversion in which no control line or I2C line changes],
  [reciprocity], [the property $S_(i j) = S_(j i)$ of passive networks without nonreciprocal materials],
  [reference plane], [the plane at which a calibrated measurement refers],
  [return loss], [$- 20 log_10 abs(Gamma)$, how far below the incident wave a reflection is],
  [REV], [rotating element electric field vector, the classical power only calibration method],
  [RF], [radio frequency],
  [S-parameters], [scattering parameters: ratios of outgoing to incoming waves at a network's ports],
  [S11], [reflection at port 1 with the other ports matched],
  [S21], [transmission from port 1 to port 2 with the other ports matched],
  [SIM-NNN], [a simulation task that fixes a design input],
  [SINR, SIR], [signal to interference plus noise ratio; signal to interference ratio],
  [SMA], [a threaded coaxial connector family used on the boards],
  [spatial covariance $vb(R)$], [the $4 times 4$ matrix of correlations between element signals; all power measurements through any pattern are linear in it],
  [SPDT], [single pole double throw switch],
  [stack-up], [the layer construction of a printed circuit board],
  [state correlated error], [a measurement error that depends on the commanded beam state, and so imitates a calibration coefficient],
  [steering vector], [the vector of element phases a plane wave from a given direction produces],
  [switched line phase shifter], [a phase shifter selecting between printed lines of different length],
  [Touchstone], [the text file format for S-parameters, `.sNp`],
  [TRL], [thru reflect line calibration],
  [VNA], [vector network analyser: measures complex S-parameters],
  [VSWR], [voltage standing wave ratio, $( 1 + abs(Gamma) ) \/ ( 1 - abs(Gamma) )$],
  [Wilkinson divider], [a matched, isolated power divider with quarter wave arms and an isolation resistor],
)
