"""The Rev A stack-up, read from one canonical file by every tool.

Decision 0009 selects the stack-up. Its numbers live in exactly one place,
``hardware/rev-a/stackup/reva-stackup.json``, and everything else reads them
from there: this module, the SIM-001 geometry, any PyAEDT or ADS set-up, and the
tables in the documentation, which are generated by ``python -m rfkit.cli
stackup --markdown`` and checked by the tests.

Three rules, each the reason this module exists:

- **Every number carries its unit, its status and its source.** The status is
  one of ``guaranteed`` (a published fabrication or laminate specification
  limit), ``typical`` (a laminate vendor's typical value), ``nominal`` (a value a
  design tool or a fabricator's calculator uses) or ``assumed`` (an engineering
  assumption, named in decision 0009). A typical value is never read as a
  tolerance.
- **Nominal and tolerance are kept apart.** A construction holds nominal values
  only. Tolerances sit in their own block, as bounds with no distribution,
  because no source gives statistics. A bound nobody publishes is
  ``unbounded``, with no number, rather than guessed.
- **Nothing here freezes RF geometry.** Every width and length computed below is
  a seed for SIM-001 or a feasibility estimate, and is labelled so. The
  canonical file may not hold a trace width, a line length or a patch
  dimension, and the tests enforce it.

The line model is scikit-rf's ``MLine``: Hammerstad and Jensen for the
quasi-static impedance and effective permittivity, with their finite thickness
correction, and Kirschning and Jansen for dispersion. The dielectric is held
frequency invariant at the stated value, smooth copper is assumed, and both
choices are recorded in the canonical file's ``simulation_model`` block.
"""
from __future__ import annotations

import hashlib
import itertools
import json
import math
import re
import warnings
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
import skrf
from scipy.constants import c as C0
from scipy.constants import mu_0 as MU0
from scipy.optimize import brentq
from skrf.media import MLine

from .budget import F0_HZ

REPO = Path(__file__).resolve().parents[2]
CANONICAL_PATH = REPO / "hardware" / "rev-a" / "stackup" / "reva-stackup.json"
#: Alternatives decision 0009 compared and did not select. Evidence only.
CANDIDATES_PATH = REPO / "hardware" / "rev-a" / "stackup" / "candidates.json"
SCHEMA = "aetherarray-stackup/1"

#: The four kinds of value the task separates, and nothing else.
STATUSES = ("guaranteed", "typical", "nominal", "assumed")
#: A tolerance bound may also be absent, which is said rather than guessed.
BOUND_STATUSES = STATUSES + ("unbounded",)

#: Units a quantity may carry, and their factor to SI.
UNITS = {"m": 1.0, "mm": 1e-3, "um": 1e-6, "Hz": 1.0, "MHz": 1e6, "GHz": 1e9,
         "S/m": 1.0, "1": 1.0}

QUANTITY_KEYS = {"value", "unit", "status", "source", "frequency_hz", "method", "note"}
BOUND_KEYS = {"parameter", "kind", "minus", "plus", "unit", "status", "source", "basis", "note"}

#: The model input each tolerance perturbs. All four are reserved for every
#: construction, bounded or not, so a tolerance study never silently skips one.
TOLERANCE_PARAMETERS = {
    "rf_dielectric_thickness": "h",
    "rf_dielectric_permittivity": "er",
    "rf_copper_thickness": "t",
    "etched_width": "w",
}

#: Key names that would freeze RF geometry if they appeared in the canonical
#: file. Geometry is decided by SIM-001 and at layout, never by the stack-up.
FROZEN_GEOMETRY = re.compile(
    r"^(trace_?width|w_?50(_seed)?|w_?70(_7)?|line_?length|delay_?length|"
    r"patch_?(length|width)|l_?patch|w_?patch|feed_?(offset|inset|position)|"
    r"element_?spacing)$",
    re.I,
)

NP_TO_DB = 20.0 / math.log(10.0)  # 8.686 dB per neper, field quantities

#: Bits of the switched line phase shifter, decision 0003, and their sum, the
#: longest differential delay any channel can carry.
BIT_DEG = (45.0, 90.0, 180.0)
LONGEST_STATE_DEG = sum(BIT_DEG)

#: Element spacing used only to size the antenna board for a feasibility check:
#: half the free space wavelength at f0, as published by decision 0004. Not a
#: design value of this module and never written back anywhere.
SPACING_FOR_SIZE_CHECK_M = 0.5 * C0 / F0_HZ


class StackupError(ValueError):
    """The canonical file is malformed, or breaks one of the rules above."""


# ----------------------------------------------------------------- data model
@dataclass(frozen=True)
class Quantity:
    """One number with its unit, its status and where it came from."""

    value: float
    unit: str
    status: str
    source: str
    frequency_hz: float | None = None
    method: str = ""
    note: str = ""

    @property
    def si(self) -> float:
        return self.value * UNITS[self.unit]


@dataclass(frozen=True)
class Bound:
    """A min-max tolerance on one model input, with no distribution."""

    key: str
    parameter: str
    kind: str          # "relative" (fraction of nominal) or "absolute"
    minus: float | None
    plus: float | None
    unit: str
    status: str
    source: str
    basis: str = ""
    note: str = ""

    @property
    def bounded(self) -> bool:
        return self.status != "unbounded"

    def interval(self, nominal_si: float) -> tuple[float, float]:
        """Low and high values in SI. Raises if the bound is not known."""
        if not self.bounded:
            raise StackupError(f"tolerance {self.key} is unbounded: {self.note}")
        if self.kind == "relative":
            return nominal_si * (1.0 - self.minus), nominal_si * (1.0 + self.plus)
        k = UNITS[self.unit]
        return nominal_si - self.minus * k, nominal_si + self.plus * k


@dataclass(frozen=True)
class Construction:
    """One board's build, as the selected fabrication process defines it."""

    key: str
    raw: dict
    materials: dict

    @property
    def board(self) -> str:
        return self.raw["board"]

    @property
    def layers(self) -> list[dict]:
        return self.raw["layers"]

    def layer(self, name: str) -> dict:
        for layer in self.layers:
            if layer["name"] == name:
                return layer
        raise StackupError(f"{self.key}: no layer named {name}")

    @property
    def rf(self) -> dict:
        return self.raw["rf_line"]

    def _q(self, d: dict) -> Quantity:
        return Quantity(**d)

    @property
    def substrate_layers(self) -> list[dict]:
        return [self.layer(n) for n in self.rf["substrate_layers"]]

    @property
    def substrate_material(self) -> dict:
        names = {layer["material"] for layer in self.substrate_layers}
        if len(names) != 1:
            raise StackupError(f"{self.key}: the RF substrate mixes materials {sorted(names)}")
        return self.materials[names.pop()]

    @property
    def h(self) -> Quantity:
        """Dielectric thickness between the RF trace and its reference plane."""
        layers = self.substrate_layers
        if len(layers) != 1:
            raise StackupError(f"{self.key}: expected one substrate layer under the RF trace")
        return self._q(layers[0]["thickness"])

    @property
    def er(self) -> Quantity:
        return self._q(self.substrate_material["permittivity"])

    @property
    def tand(self) -> Quantity:
        return self._q(self.substrate_material["loss_tangent"])

    @property
    def t(self) -> Quantity:
        """Finished copper thickness of the RF signal layer."""
        return self._q(self.layer(self.rf["signal_layer"])["thickness"])

    @property
    def sigma(self) -> Quantity:
        cu = self.materials[self.layer(self.rf["signal_layer"])["material"]]
        return self._q(cu["conductivity"])

    @property
    def finished_thickness(self) -> Quantity:
        return self._q(self.raw["finished_thickness"])


@dataclass(frozen=True)
class Stackup:
    raw: dict
    path: Path | None = None
    sha256: str | None = None
    constructions: dict = field(default_factory=dict)
    tolerances: dict = field(default_factory=dict)

    @property
    def id(self) -> str:
        return self.raw["id"]

    @property
    def fingerprint(self) -> str:
        """Identifier plus content hash, carried by every trace built on it.

        The identifier alone would survive an edit that forgot to bump the
        revision; the hash does not.
        """
        return f"{self.id}:{(self.sha256 or 'in-memory')[:12]}"

    @property
    def simulation_model(self) -> dict:
        return self.raw["simulation_model"]

    def construction(self, key: str) -> Construction:
        try:
            return self.constructions[key]
        except KeyError:
            raise StackupError(f"no construction {key!r}; have {sorted(self.constructions)}")


# ----------------------------------------------------------------- validation
def _is_number(x) -> bool:
    return isinstance(x, (int, float)) and not isinstance(x, bool) and math.isfinite(x)


def _check_quantity(d: dict, where: str, sources: dict, problems: list) -> None:
    extra = set(d) - QUANTITY_KEYS
    if extra:
        problems.append(f"{where}: keys {sorted(extra)} do not belong in a nominal quantity "
                        "(tolerances go in the tolerances block)")
    for k in ("value", "unit", "status", "source"):
        if k not in d:
            problems.append(f"{where}: missing {k}")
    if "value" in d and not _is_number(d["value"]):
        problems.append(f"{where}: value must be a finite number")
    if d.get("unit") not in UNITS:
        problems.append(f"{where}: unit {d.get('unit')!r} is not one of {sorted(UNITS)}")
    if d.get("status") not in STATUSES:
        problems.append(f"{where}: status {d.get('status')!r} is not one of {STATUSES}")
    if d.get("source") not in sources:
        problems.append(f"{where}: source {d.get('source')!r} is not in the sources block")
    if d.get("frequency_hz") is not None and not _is_number(d["frequency_hz"]):
        problems.append(f"{where}: frequency_hz must be a number or null")


def _walk(node, where: str, sources: dict, problems: list) -> None:
    if isinstance(node, dict):
        for k in node:
            if FROZEN_GEOMETRY.match(str(k)):
                problems.append(f"{where}.{k}: RF geometry may not be frozen in the stack-up")
        if "value" in node:
            _check_quantity(node, where, sources, problems)
            return
        for k, v in node.items():
            _walk(v, f"{where}.{k}", sources, problems)
    elif isinstance(node, list):
        for i, v in enumerate(node):
            name = v.get("name", i) if isinstance(v, dict) else i
            _walk(v, f"{where}[{name}]", sources, problems)


def _check_bound(key: str, d: dict, where: str, sources: dict, problems: list) -> None:
    extra = set(d) - BOUND_KEYS
    if extra:
        problems.append(f"{where}: keys {sorted(extra)} are not allowed; bounds carry no "
                        "distribution and no nominal value")
    if d.get("parameter") != TOLERANCE_PARAMETERS.get(key):
        problems.append(f"{where}: parameter must be {TOLERANCE_PARAMETERS.get(key)!r}")
    if d.get("kind") not in ("relative", "absolute"):
        problems.append(f"{where}: kind must be relative or absolute")
    if d.get("unit") not in UNITS:
        problems.append(f"{where}: unit {d.get('unit')!r} is not one of {sorted(UNITS)}")
    if d.get("kind") == "relative" and d.get("unit") != "1":
        problems.append(f"{where}: a relative bound is a fraction, unit '1'")
    if d.get("status") not in BOUND_STATUSES:
        problems.append(f"{where}: status {d.get('status')!r} is not one of {BOUND_STATUSES}")
    if d.get("source") not in sources:
        problems.append(f"{where}: source {d.get('source')!r} is not in the sources block")
    if d.get("status") == "unbounded":
        if d.get("minus") is not None or d.get("plus") is not None:
            problems.append(f"{where}: an unbounded tolerance carries no number")
        if not d.get("note"):
            problems.append(f"{where}: an unbounded tolerance must say how it will be bounded")
    else:
        for side in ("minus", "plus"):
            if not _is_number(d.get(side)) or d[side] < 0:
                problems.append(f"{where}: {side} must be a non-negative number")


def validate(raw: dict) -> list[str]:
    """Every rule the canonical file must satisfy. Empty means valid."""
    problems: list[str] = []
    if raw.get("schema") != SCHEMA:
        problems.append(f"schema must be {SCHEMA!r}")
    for k in ("id", "revision", "status", "date", "decision", "sources", "materials",
              "constructions", "tolerances", "simulation_model"):
        if k not in raw:
            problems.append(f"missing top level key {k}")
    if problems:
        return problems
    sources = raw["sources"]
    for sid, s in sources.items():
        for k in ("title", "kind", "consulted"):
            if not s.get(k):
                problems.append(f"sources.{sid}: missing {k}")
        if s.get("kind") in ("fabricator", "laminate_vendor") and not s.get("url"):
            problems.append(f"sources.{sid}: a vendor source needs a url")
    for section in ("materials", "constructions", "simulation_model"):
        _walk(raw[section], section, sources, problems)
    for name, choice in raw["simulation_model"].items():
        if choice.get("status") not in STATUSES or choice.get("source") not in sources:
            problems.append(f"simulation_model.{name}: needs a status and a known source")
        if not choice.get("model"):
            problems.append(f"simulation_model.{name}: needs a model")
    for key, cons in raw["constructions"].items():
        names = [layer.get("name") for layer in cons.get("layers", [])]
        rf = cons.get("rf_line", {})
        for role in ("signal_layer", "reference_layer"):
            if rf.get(role) not in names:
                problems.append(f"constructions.{key}.rf_line.{role} names no layer")
        for name in rf.get("substrate_layers", []):
            if name not in names:
                problems.append(f"constructions.{key}.rf_line.substrate_layers: {name} is no layer")
        if rf.get("signal_layer") in names and rf.get("reference_layer") in names:
            i, j = names.index(rf["signal_layer"]), names.index(rf["reference_layer"])
            between = names[min(i, j) + 1:max(i, j)]
            if between != rf.get("substrate_layers"):
                problems.append(f"constructions.{key}: the RF reference plane is not the next "
                                "copper layer; substrate_layers must be exactly the layers between")
        for layer in cons.get("layers", []):
            if layer.get("material") not in raw["materials"]:
                problems.append(f"constructions.{key}: layer {layer.get('name')} has unknown "
                                f"material {layer.get('material')!r}")
        bounds = raw["tolerances"].get(key)
        if bounds is None:
            problems.append(f"tolerances.{key}: missing; every construction reserves its bounds")
            continue
        for tkey in TOLERANCE_PARAMETERS:
            if tkey not in bounds:
                problems.append(f"tolerances.{key}.{tkey}: reserved parameter missing")
        for tkey, d in bounds.items():
            if tkey not in TOLERANCE_PARAMETERS:
                problems.append(f"tolerances.{key}.{tkey}: unknown tolerance")
                continue
            _check_bound(tkey, d, f"tolerances.{key}.{tkey}", sources, problems)
    return problems


def _build(raw: dict, path: Path | None, sha: str | None) -> Stackup:
    problems = validate(raw)
    if problems:
        raise StackupError("invalid stack-up:\n  " + "\n  ".join(problems))
    cons = {k: Construction(key=k, raw=v, materials=raw["materials"])
            for k, v in raw["constructions"].items()}
    tols = {k: {tk: Bound(key=tk, **{f: d.get(f) for f in BOUND_KEYS if f in d})
                for tk, d in v.items()}
            for k, v in raw["tolerances"].items()}
    return Stackup(raw=raw, path=path, sha256=sha, constructions=cons, tolerances=tols)


def load(path: Path | str | None = None) -> Stackup:
    """Read and validate the canonical stack-up. Raises :class:`StackupError`."""
    path = Path(path) if path is not None else CANONICAL_PATH
    data = path.read_bytes()
    raw = json.loads(data.decode("utf-8"))
    return _build(raw, path, hashlib.sha256(data).hexdigest())


def from_dict(raw: dict) -> Stackup:
    """Validate an in-memory stack-up, for tests and candidate comparisons."""
    return _build(raw, None, None)


def load_candidates(path: Path | str | None = None) -> Stackup:
    """The rejected alternatives, validated by the same rules. Never simulated."""
    return load(path if path is not None else CANDIDATES_PATH)


# ----------------------------------------------------------------- line model
@dataclass(frozen=True)
class Line:
    """Microstrip properties at one frequency, from the scikit-rf model."""

    w_m: float
    f_hz: float
    z0_ohm: float
    eeff: float
    alpha_c_db_per_m: float
    alpha_d_db_per_m: float

    @property
    def lambda_g_m(self) -> float:
        return C0 / (self.f_hz * math.sqrt(self.eeff))

    @property
    def alpha_db_per_m(self) -> float:
        return self.alpha_c_db_per_m + self.alpha_d_db_per_m


def line(h_m: float, er: float, w_m: float, t_m: float, f_hz: float = F0_HZ,
         tand: float = 0.0, sigma: float = 5.8e7) -> Line:
    """Hammerstad and Jensen with Kirschning and Jansen dispersion, smooth copper."""
    freq = skrf.Frequency.from_f([f_hz], unit="Hz")
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        m = MLine(frequency=freq, w=w_m, h=h_m, t=t_m, ep_r=er, tand=tand,
                  rho=1.0 / sigma, rough=0.0, model="hammerstadjensen",
                  disp="kirschningjansen", diel="frequencyinvariant", z0_port=50.0)
        return Line(
            w_m=w_m, f_hz=f_hz,
            z0_ohm=float(np.real(m.z0_characteristic[0])),
            eeff=float(np.real(m.ep_reff_f[0])),
            alpha_c_db_per_m=float(np.real(m.alpha_conductor[0])) * NP_TO_DB,
            alpha_d_db_per_m=float(np.real(m.alpha_dielectric[0])) * NP_TO_DB,
        )


def solve_width(z0_ohm: float, h_m: float, er: float, t_m: float, f_hz: float = F0_HZ,
                tand: float = 0.0, sigma: float = 5.8e7) -> float:
    """Width at which the model's characteristic impedance equals ``z0_ohm``."""
    def err(w):
        return line(h_m, er, w, t_m, f_hz, tand, sigma).z0_ohm - z0_ohm
    return float(brentq(err, 0.01 * h_m, 40.0 * h_m, xtol=1e-10))


def closed_form_width(z0_ohm: float, er: float, h_m: float) -> float:
    """Wheeler and Hammerstad synthesis, zero thickness, quasi-static.

    Pozar, Microwave Engineering, 4th edition, equation 3.197. An independent
    check on :func:`solve_width`, not a second answer.
    """
    a = z0_ohm / 60.0 * math.sqrt((er + 1) / 2) + (er - 1) / (er + 1) * (0.23 + 0.11 / er)
    w_over_h = 8 * math.exp(a) / (math.exp(2 * a) - 2)
    if w_over_h > 2:
        b = 377 * math.pi / (2 * z0_ohm * math.sqrt(er))
        w_over_h = 2 / math.pi * (b - 1 - math.log(2 * b - 1) + (er - 1) / (2 * er)
                                  * (math.log(b - 1) + 0.39 - 0.61 / er))
    return w_over_h * h_m


def filling_factor(h_m: float, w_m: float) -> float:
    """``F`` in the quasi-static effective permittivity, Pozar equation 3.195."""
    return 1.0 / math.sqrt(1.0 + 12.0 * h_m / w_m)


def closed_form_eeff(er: float, h_m: float, w_m: float) -> float:
    return (er + 1) / 2 + (er - 1) / 2 * filling_factor(h_m, w_m)


def phase_error_deg(theta_deg: float, eeff_design: float, eeff_actual: float) -> float:
    """Error of an electrical length laid out for one permittivity, realised on another.

    Exact for a uniform line: the physical length is fixed, so the realised
    phase scales with the square root of the effective permittivity.
    """
    return theta_deg * (math.sqrt(eeff_actual / eeff_design) - 1.0)


def first_order_phase_error_deg(theta_deg: float, er: float, h_m: float, w_m: float,
                                d_er: float) -> float:
    """The same error to first order in the substrate permittivity, quasi-static.

    ``d phi / phi = (1/2) d eeff / eeff`` and ``d eeff / d er = (1 + F) / 2``.
    """
    f = filling_factor(h_m, w_m)
    return 0.5 * theta_deg * (1 + f) / 2 * d_er / closed_form_eeff(er, h_m, w_m)


# ----------------------------------------------------------------- derived, non-final
def _nominal(c: Construction) -> dict:
    return {"h": c.h.si, "er": c.er.value, "t": c.t.si, "tand": c.tand.value,
            "sigma": c.sigma.si}


def seed(st: Stackup, key: str, z0_ohm: float = 50.0, f_hz: float = F0_HZ) -> dict:
    """A width seed for SIM-001 and what follows from it. **Initialisation only.**

    The returned width is ``W_seed``, not the final width. SIM-001 decides the
    width; layout takes it from SIM-001, never from here.
    """
    c = st.construction(key)
    p = _nominal(c)
    w = solve_width(z0_ohm, p["h"], p["er"], p["t"], f_hz, p["tand"], p["sigma"])
    ln = line(p["h"], p["er"], w, p["t"], f_hz, p["tand"], p["sigma"])
    wcf = closed_form_width(z0_ohm, p["er"], p["h"])
    return {
        "label": "INITIALISATION ONLY: W_seed is not the final width; SIM-001 decides it",
        "construction": key, "stackup": st.fingerprint, "z0_target_ohm": z0_ohm, "f_hz": f_hz,
        "w_seed_m": w, "w_closed_form_m": wcf,
        "w_seed_vs_closed_form": w / wcf - 1.0,
        "eeff": ln.eeff, "eeff_closed_form": closed_form_eeff(p["er"], p["h"], w),
        "lambda0_m": C0 / f_hz, "lambda_g_m": ln.lambda_g_m,
        "length_for_deg_m": {f"{d:g}": d / 360.0 * ln.lambda_g_m
                             for d in BIT_DEG + (LONGEST_STATE_DEG,)},
        "alpha_c_db_per_m": ln.alpha_c_db_per_m, "alpha_d_db_per_m": ln.alpha_d_db_per_m,
        "model": "scikit-rf MLine: hammerstadjensen, kirschningjansen, frequency invariant "
                 "dielectric, smooth copper",
    }


#: Lead pitch of the SC-70-6 package the PE4259-63 comes in, decision 0003. A 50
#: ohm line much wider than this needs a taper at every one of the 87 switch RF
#: pins, and each taper is one more discontinuity to model.
SC70_PITCH_M = 0.65e-3


def width_flags(st: Stackup, key: str, w_m: float) -> list[str]:
    """Fabrication and layout sanity of a line width. Empty means unremarkable."""
    c = st.construction(key)
    rules = c.raw.get("rules", {})
    flags = []
    if "min_trace" in rules:
        wmin = Quantity(**rules["min_trace"]).si
        if w_m < 2 * wmin:
            flags.append(f"narrow: under twice the {wmin * 1e3:.3f} mm process minimum")
    if "beamformer" in c.board and w_m > SC70_PITCH_M:
        flags.append("wide: over the SC-70-6 lead pitch, a taper at every switch pin")
    return flags


def sensitivity(st: Stackup, key: str, w_m: float | None = None,
                f_hz: float = F0_HZ) -> dict:
    """One at a time and all-corner effect of each bounded tolerance.

    Evaluated at the seed width with every other input nominal. The phase is the
    error of a line laid out for the nominal effective permittivity, for each
    bit and for the longest state. Bounds only: no statistics are implied, so
    the combined figure is the worst corner, not a root sum of squares.
    """
    c = st.construction(key)
    p = _nominal(c)
    if w_m is None:
        w_m = seed(st, key, f_hz=f_hz)["w_seed_m"]
    p["w"] = w_m
    base = line(p["h"], p["er"], w_m, p["t"], f_hz, p["tand"], p["sigma"])
    thetas = BIT_DEG + (LONGEST_STATE_DEG,)

    def evaluate(q):
        ln = line(q["h"], q["er"], q["w"], q["t"], f_hz, q["tand"], q["sigma"])
        return {"z0_ohm": ln.z0_ohm, "eeff": ln.eeff,
                "phase_error_deg": {f"{d:g}": phase_error_deg(d, base.eeff, ln.eeff)
                                    for d in thetas}}

    rows, intervals, unbounded = {}, {}, []
    for tkey, b in st.tolerances[key].items():
        name = b.parameter
        if not b.bounded:
            unbounded.append(tkey)
            continue
        lo, hi = b.interval(p[name])
        intervals[name] = (lo, hi)
        rows[tkey] = {"status": b.status, "low": evaluate({**p, name: lo}),
                      "high": evaluate({**p, name: hi})}
    corners = []
    names = sorted(intervals)
    for combo in itertools.product(*(intervals[n] for n in names)):
        corners.append(evaluate({**p, **dict(zip(names, combo))}))
    worst = {f"{d:g}": max(abs(r["phase_error_deg"][f"{d:g}"]) for r in corners)
             for d in thetas} if corners else {}
    z0s = [r["z0_ohm"] for r in corners]
    return {"construction": key, "w_m": w_m, "nominal": {"z0_ohm": base.z0_ohm, "eeff": base.eeff},
            "one_at_a_time": rows, "unbounded": unbounded,
            "worst_corner_phase_error_deg": worst,
            "z0_range_ohm": (min(z0s), max(z0s)) if z0s else None}


def state_loss_spread_db(st: Stackup, key: str, roughness_factor: float = 1.0,
                         f_hz: float = F0_HZ) -> float:
    """Extra loss of the longest switched line state over the shortest.

    The delay arms of all three bits add ``315/360`` of a guided wavelength. The
    loss of that extra length is a state dependent amplitude, which the diagonal
    state cannot absorb. ``roughness_factor`` multiplies conductor loss only.
    """
    s = seed(st, key, f_hz=f_hz)
    alpha = s["alpha_c_db_per_m"] * roughness_factor + s["alpha_d_db_per_m"]
    return alpha * s["length_for_deg_m"][f"{LONGEST_STATE_DEG:g}"]


def patch_sanity(st: Stackup, key: str, f_hz: float = F0_HZ) -> dict:
    """Order of magnitude rectangular patch figures. **Sanity check only.**

    Transmission line model, Balanis, Antenna Theory, equations 14-1, 14-2, 14-6
    and 14-7, and the Jackson and Alexopoulos bandwidth estimate. None of these
    is a design value: the patch is optimised in HFSS later and its length,
    width, feed and spacing stay free parameters until then.
    """
    c = st.construction(key)
    h, er, tand, sigma = c.h.si, c.er.value, c.tand.value, c.sigma.si
    lam0 = C0 / f_hz
    w = C0 / (2 * f_hz) * math.sqrt(2 / (er + 1))

    def length_for(er_):
        ee = closed_form_eeff(er_, h, w)
        dl = 0.412 * h * (ee + 0.3) * (w / h + 0.264) / ((ee - 0.258) * (w / h + 0.8))
        return C0 / (2 * f_hz * math.sqrt(ee)) - 2 * dl, ee, dl

    length, eeff, dl = length_for(er)

    def resonance(er_):
        ee = closed_form_eeff(er_, h, w)
        dl_ = 0.412 * h * (ee + 0.3) * (w / h + 0.264) / ((ee - 0.258) * (w / h + 0.8))
        return C0 / (2 * (length + 2 * dl_) * math.sqrt(ee))

    bw = 3.77 * (er - 1) / er ** 2 * (w / length) * (h / lam0)
    q_rad = 1 / (math.sqrt(2) * bw)
    q_d = 1 / tand
    q_c = h * math.sqrt(math.pi * f_hz * MU0 * sigma)
    efficiency = (1 / q_rad) / (1 / q_rad + 1 / q_d + 1 / q_c)
    out = {"label": "SANITY CHECK ONLY: not a design value; HFSS optimises the patch later",
           "construction": key, "w_patch_m": w, "l_patch_m": length, "eeff": eeff,
           "fractional_bandwidth_vswr2": bw, "radiation_efficiency": efficiency,
           "q_rad": q_rad, "q_d": q_d, "q_c": q_c, "lambda0_m": lam0}
    b = st.tolerances[key]["rf_dielectric_permittivity"]
    if b.bounded:
        lo, hi = b.interval(er)
        out["resonance_shift_for_dk_bounds"] = (resonance(hi) / f_hz - 1, resonance(lo) / f_hz - 1)
    out["board_length_estimate_m"] = 3 * SPACING_FOR_SIZE_CHECK_M + w + 2 * 6 * h + 2 * 0.01
    return out


# ----------------------------------------------------------------- SIM-001 inputs
#: SIM-001 solver settings that are choices, recorded once here and echoed into
#: the metadata. Decision 0007 asks for the convergence criterion with every
#: solve; 0.02 satisfies its bound of about 0.04 |S21| for any |S21| above 0.5.
SIM001_SETTINGS = {
    "solution_frequency_hz": F0_HZ,
    "sweep_start_hz": 1.0e9,
    "sweep_stop_hz": 3.0e9,
    "sweep_step_hz": 5.0e6,
    "max_delta_s": 0.02,
    "min_converged_passes": 2,
    "max_passes": 20,
    "port_impedance_ohm": 50.0,
    "width_factors": (0.9, 1.0, 1.1),
}


def sim001_parameters(st: Stackup, key: str = "beamformer") -> dict:
    """Every number the SIM-001 model needs, generated from the canonical file.

    Lengths are those of a two line pair whose difference is a quarter guided
    wavelength at f0, so that the same pair, as a coupon, extracts the
    propagation constant over 1 to 3 GHz without approaching a half wavelength
    singularity. Port and box sizes are starting values that SIM-001 itself
    checks by enlarging them; they are not sacred.
    """
    c = st.construction(key)
    s = seed(st, key)
    w, h, t = s["w_seed_m"], c.h.si, c.t.si
    #: The short line is long enough for the port's evanescent modes to die out
    #: many times over, at about fifty substrate heights; the long one adds a
    #: quarter guided wavelength, rounded to 0.1 mm.
    l_short = 10e-3
    l_long = l_short + round(0.25 * s["lambda_g_m"] * 1e4) / 1e4
    sm = st.simulation_model
    return {
        "task": "SIM-001",
        "stackup": st.fingerprint,
        "construction": key,
        "label": "W values are seeds; SIM-001 decides the 50 ohm width",
        "variables_mm": {
            "sub_h": round(h * 1e3, 6),
            "cu_t": round(t * 1e3, 6),
            "w_seed": round(w * 1e3, 4),
            "l_short": round(l_short * 1e3, 3),
            "l_long": round(l_long * 1e3, 3),
            "port_w": round(max(10 * w, w + 10 * h) * 1e3, 3),
            "port_h": round(10 * h * 1e3, 3),
        },
        "width_sweep_mm": [round(w * k * 1e3, 4) for k in SIM001_SETTINGS["width_factors"]],
        "materials": {
            "substrate": {"permittivity": c.er.value, "loss_tangent": c.tand.value,
                          "permittivity_status": c.er.status, "source": c.er.source},
            "copper": {"conductivity_s_per_m": c.sigma.si, "status": c.sigma.status},
        },
        "model_choices": {k: v.get("model", v.get("value")) if isinstance(v, dict) else v
                          for k, v in sm.items()},
        "settings": dict(SIM001_SETTINGS),
    }


#: What the SIM-001 metadata sidecar must contain, next to each ``.s2p``.
SIM_EXPORT_FIELDS = (
    "task", "stackup", "construction", "solver", "solver_version", "licence",
    "solution_frequency_hz", "sweep", "port_impedance_ohm", "port_definition",
    "renormalised", "mesh_elements", "adaptive_passes", "final_delta_s",
    "convergence_criterion", "boundary", "materials", "variables_mm", "touchstone",
)


def check_sim_export(meta: dict, st: Stackup | None = None) -> list[str]:
    """Problems with a SIM-001 metadata sidecar. Empty means traceable."""
    problems = [f"missing {k}" for k in SIM_EXPORT_FIELDS if k not in meta]
    if st is not None and meta.get("stackup") != st.fingerprint:
        problems.append(f"stackup {meta.get('stackup')!r} is not the canonical {st.fingerprint!r}")
    if meta.get("port_impedance_ohm") not in (None, 50, 50.0):
        problems.append("Touchstone files are renormalised to 50 ohm, the analyser's impedance")
    return problems


# ----------------------------------------------------------------- comparison
def comparison(st: Stackup, keys=None) -> list[dict]:
    """The figures decision 0009 compares, for every construction in ``st``."""
    rows = []
    for key in keys or st.constructions:
        c = st.construction(key)
        s = seed(st, key)
        sens = sensitivity(st, key, s["w_seed_m"])
        dk = sens["one_at_a_time"].get("rf_dielectric_permittivity")
        p = patch_sanity(st, key)
        rows.append({
            "key": key, "board": c.board,
            "process": f"{c.raw['fabrication']['fabricator']}, {c.raw['fabrication']['process']}",
            "h_mm": c.h.si * 1e3, "er": c.er.value, "er_status": c.er.status,
            "tand": c.tand.value, "w_seed_mm": s["w_seed_m"] * 1e3,
            "lambda_g_mm": s["lambda_g_m"] * 1e3,
            "loss_spread_db": (state_loss_spread_db(st, key, 1.0),
                               state_loss_spread_db(st, key, 2.0)),
            "dk_phase_315_deg": (max(abs(dk["low"]["phase_error_deg"]["315"]),
                                     abs(dk["high"]["phase_error_deg"]["315"]))
                                 if dk else None),
            "dk_bound_status": st.tolerances[key]["rf_dielectric_permittivity"].status,
            "patch_bandwidth": p["fractional_bandwidth_vswr2"],
            "patch_efficiency": p["radiation_efficiency"],
            "flags": width_flags(st, key, s["w_seed_m"]),
            "cost_class": c.raw["fabrication"].get("cost_class", "not recorded"),
        })
    return rows


# ----------------------------------------------------------------- documentation
#: Documents that embed generated blocks. A block is the text between
#: ``<!-- stackup:begin NAME -->`` and ``<!-- stackup:end NAME -->``; the tests
#: regenerate every block and fail if the document differs. Remove a document
#: from this list only when a later decision supersedes it.
GENERATED_DOCS = (
    "hardware/rev-a/stackup/README.md",
    "decisions/0009-rev-a-stack-up.md",
    "experiments/SIM-001-microstrip-50-ohm.md",
    "docs/aetherarray-master-reference.md",
)
_BLOCK = re.compile(r"(<!-- stackup:begin (\S+) -->\n)(.*?)(<!-- stackup:end \2 -->)", re.S)


def _mm(x_m: float, nd: int = 2) -> str:
    return f"{x_m * 1e3:.{nd}f}"


def _qty(q: dict) -> str:
    unit = "" if q["unit"] == "1" else f" {q['unit']}"
    return f"{q['value']:g}{unit}"


def render_nominal(st: Stackup, cand: Stackup | None = None) -> str:
    out = []
    for key, c in st.constructions.items():
        out += [f"**{key}**, {c.board}: {c.raw['fabrication']['fabricator']}, "
                f"{c.raw['fabrication']['process']}.", "",
                "| Layer | Material | Role | Thickness | Status | Source |",
                "| --- | --- | --- | --- | --- | --- |"]
        for layer in c.layers:
            t = layer["thickness"]
            out.append(f"| {layer['name']} | {layer['material']} | {layer['role']} | "
                       f"{t['value']:g} {t['unit']} | {t['status']} | {t['source']} |")
        out.append("")
    out += ["| Material | Designation |", "| --- | --- |"]
    out += [f"| {name} | {m['designation']} |" for name, m in st.raw["materials"].items()]
    out += ["", "| Material | Property | Value | Status | Source | Frequency and method |",
            "| --- | --- | --- | --- | --- | --- |"]
    for name, m in st.raw["materials"].items():
        for prop in ("permittivity", "loss_tangent", "conductivity"):
            if prop not in m:
                continue
            q = m[prop]
            if prop == "conductivity":
                freq = "not applicable"
            else:
                freq = f"{q['frequency_hz'] / 1e9:g} GHz" if q.get("frequency_hz") else "not stated"
            how = f"{freq}; {q['method']}" if q.get("method") else freq
            out.append(f"| {name} | {prop.replace('_', ' ')} | {_qty(q)} | {q['status']} | "
                       f"{q['source']} | {how} |")
    return "\n".join(out) + "\n"


def render_tolerances(st: Stackup, cand: Stackup | None = None) -> str:
    out = ["| Construction | Tolerance | Input | Bound | Status | Source |",
           "| --- | --- | --- | --- | --- | --- |"]
    for key, bounds in st.tolerances.items():
        for tkey, b in bounds.items():
            if not b.bounded:
                bound = "unbounded, no number"
            elif b.kind == "relative":
                bound = f"minus {b.minus * 100:g} to plus {b.plus * 100:g} per cent"
            else:
                unit = "" if b.unit == "1" else f" {b.unit}"
                bound = f"minus {b.minus:g} to plus {b.plus:g}{unit}"
            out.append(f"| {key} | {tkey.replace('_', ' ')} | ${b.parameter}$ | {bound} | "
                       f"{b.status} | {b.source} |")
    return "\n".join(out) + "\n"


def render_seeds(st: Stackup, cand: Stackup | None = None) -> str:
    out = ["**INITIALISATION ONLY.** $W_{\\text{seed}} \\neq W_{50}$. SIM-001 decides "
           "the width; every length below is a feasibility estimate, not a layout value.", "",
           "| Construction | Quantity | Value |", "| --- | --- | --- |"]
    for key in st.constructions:
        s = seed(st, key)
        rows = [
            ("$W_{\\text{seed}}$ for 50 ohm", f"{_mm(s['w_seed_m'], 3)} mm"),
            ("closed form check, zero thickness", f"{_mm(s['w_closed_form_m'], 3)} mm"),
            ("$\\varepsilon_{\\text{eff}}$ at $f_0$", f"{s['eeff']:.3f}"),
            ("$\\lambda_0$", f"{_mm(s['lambda0_m'], 1)} mm"),
            ("$\\lambda_g$", f"{_mm(s['lambda_g_m'], 1)} mm"),
        ]
        rows += [(f"line for {d} degrees", f"{_mm(v, 1)} mm")
                 for d, v in s["length_for_deg_m"].items()]
        if key == "beamformer":
            p = _nominal(st.construction(key))
            w70 = solve_width(70.7, p["h"], p["er"], p["t"], tand=p["tand"], sigma=p["sigma"])
            rows.append(("$W_{\\text{seed}}$ for 70.7 ohm, Wilkinson arms", f"{_mm(w70, 3)} mm"))
        flags = width_flags(st, key, s["w_seed_m"])
        rows.append(("width flags", "; ".join(flags) if flags else "none"))
        out += [f"| {key} | {q} | {v} |" for q, v in rows]
    return "\n".join(out) + "\n"


def render_sensitivity(st: Stackup, cand: Stackup | None = None) -> str:
    out = ["Each bound applied alone at the seed width, then the worst of every corner. "
           "Phase is the error of a line laid out for the nominal permittivity.", "",
           "| Construction | Tolerance | Status | $Z_0$ (ohm) | 180 degree error (deg) | "
           "315 degree error (deg) |", "| --- | --- | --- | --- | --- | --- |"]
    for key in st.constructions:
        r = sensitivity(st, key)
        for tkey, row in r["one_at_a_time"].items():
            lo, hi = row["low"], row["high"]
            out.append(f"| {key} | {tkey.replace('_', ' ')} | {row['status']} | "
                       f"{lo['z0_ohm']:.1f} to {hi['z0_ohm']:.1f} | "
                       f"{lo['phase_error_deg']['180']:+.2f} to {hi['phase_error_deg']['180']:+.2f} | "
                       f"{lo['phase_error_deg']['315']:+.2f} to {hi['phase_error_deg']['315']:+.2f} |")
        for tkey in r["unbounded"]:
            out.append(f"| {key} | {tkey.replace('_', ' ')} | unbounded | not computed | "
                       "not computed | not computed |")
        z = r["z0_range_ohm"]
        w = r["worst_corner_phase_error_deg"]
        out.append(f"| {key} | worst corner of the bounds above | combined | "
                   f"{z[0]:.1f} to {z[1]:.1f} | {w['180']:.2f} | {w['315']:.2f} |")
    return "\n".join(out) + "\n"


def render_loss(st: Stackup, cand: Stackup | None = None) -> str:
    out = ["| Construction | Conductor loss (dB/m) | Dielectric loss (dB/m) | "
           "Extra loss of the 315 degree state, smooth copper (dB) | "
           "Same, conductor loss doubled (dB) |", "| --- | --- | --- | --- | --- |"]
    for key in st.constructions:
        s = seed(st, key)
        out.append(f"| {key} | {s['alpha_c_db_per_m']:.2f} | {s['alpha_d_db_per_m']:.2f} | "
                   f"{state_loss_spread_db(st, key, 1.0):.2f} | "
                   f"{state_loss_spread_db(st, key, 2.0):.2f} |")
    return "\n".join(out) + "\n"


def render_patch(st: Stackup, cand: Stackup | None = None) -> str:
    out = ["**SANITY CHECK ONLY.** The patch length, width, feed and spacing stay free "
           "parameters for HFSS. These figures only say whether a patch is physically "
           "sensible on each construction.", "",
           "| Construction | $W_p$ (mm) | $L_p$ (mm) | Bandwidth, VSWR 2 | "
           "Radiation efficiency | Resonance shift over the permittivity bound |",
           "| --- | --- | --- | --- | --- | --- |"]
    for key in st.constructions:
        p = patch_sanity(st, key)
        shift = p.get("resonance_shift_for_dk_bounds")
        shift_s = (f"{shift[0] * 100:+.2f} to {shift[1] * 100:+.2f} per cent"
                   if shift else "unbounded")
        out.append(f"| {key} | {_mm(p['w_patch_m'], 1)} | {_mm(p['l_patch_m'], 1)} | "
                   f"{p['fractional_bandwidth_vswr2'] * 100:.2f} per cent | "
                   f"{p['radiation_efficiency'] * 100:.0f} per cent | {shift_s} |")
    p = patch_sanity(st, "antenna")
    out += ["", "Four elements at half a free space wavelength need an antenna board about "
            f"{_mm(p['board_length_estimate_m'], 0)} mm long, sanity check only."]
    return "\n".join(out) + "\n"


def render_comparison(st: Stackup, cand: Stackup | None = None) -> str:
    out = ["| Construction | Process | $h$ (mm) | $\\varepsilon_r$, status | $\\tan\\delta$ | "
           "$W_{\\text{seed}}$ (mm) | $\\lambda_g$ (mm) | 315 degree loss spread, smooth to "
           "doubled conductor loss (dB) | 315 degree error from the $\\varepsilon_r$ bound (deg) | "
           "Patch bandwidth, efficiency | Width flags |",
           "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |"]
    for src, label in ((st, "selected"), (cand, "candidate")):
        if src is None:
            continue
        for r in comparison(src):
            dk = (f"{r['dk_phase_315_deg']:.1f}, {r['dk_bound_status']}"
                  if r["dk_phase_315_deg"] is not None else "unbounded")
            lo, hi = r["loss_spread_db"]
            out.append(
                f"| {r['key']}, {label} | {r['process']} | {r['h_mm']:.3f} | "
                f"{r['er']:g}, {r['er_status']} | {r['tand']:g} | {r['w_seed_mm']:.3f} | "
                f"{r['lambda_g_mm']:.1f} | {lo:.2f} to {hi:.2f} | {dk} | "
                f"{r['patch_bandwidth'] * 100:.2f} per cent, {r['patch_efficiency'] * 100:.0f} per cent | "
                f"{'; '.join(r['flags']) if r['flags'] else 'none'} |")
    return "\n".join(out) + "\n"


def render_sim001(st: Stackup, cand: Stackup | None = None) -> str:
    p = sim001_parameters(st)
    out = [f"Generated from `{st.fingerprint}`, construction `{p['construction']}`. "
           "**$W_{\\text{seed}}$ is not the final width.**", "",
           "| Variable | Value | Origin |", "| --- | --- | --- |"]
    origin = {"sub_h": "PP1 thickness", "cu_t": "L1 finished copper",
              "w_seed": "50 ohm seed, scikit-rf model", "l_short": "fixed choice",
              "l_long": "short line plus a quarter guided wavelength at $f_0$",
              "port_w": "the larger of ten widths and the width plus ten heights",
              "port_h": "ten substrate heights"}
    for k, v in p["variables_mm"].items():
        out.append(f"| `{k}` | {v:g} mm | {origin[k]} |")
    m = p["materials"]
    out += [f"| `sub_er` | {m['substrate']['permittivity']:g} | PP1 permittivity, "
            f"{m['substrate']['permittivity_status']} |",
            f"| `sub_tand` | {m['substrate']['loss_tangent']:g} | PP1 loss tangent |",
            f"| `cu_sigma` | {m['copper']['conductivity_s_per_m']:g} S/m | copper, "
            f"{m['copper']['status']} |",
            f"| width sweep | {', '.join(f'{w:g}' for w in p['width_sweep_mm'])} mm | "
            "the seed scaled by 0.9, 1.0 and 1.1 |"]
    s = p["settings"]
    out += ["", f"Solution frequency {s['solution_frequency_hz'] / 1e9:g} GHz; sweep "
            f"{s['sweep_start_hz'] / 1e9:g} to {s['sweep_stop_hz'] / 1e9:g} GHz in "
            f"{s['sweep_step_hz'] / 1e6:g} MHz steps; maximum change in S {s['max_delta_s']:g} "
            f"over {s['min_converged_passes']} consecutive passes, at most {s['max_passes']} "
            f"passes; ports renormalised to {s['port_impedance_ohm']:g} ohm."]
    return "\n".join(out) + "\n"


def permittivity_for_phase_deg(st: Stackup, key: str, limit_deg: float,
                               theta_deg: float = LONGEST_STATE_DEG) -> float:
    """Largest substrate permittivity error keeping ``theta_deg`` within ``limit_deg``."""
    c = st.construction(key)
    s = seed(st, key)
    p = _nominal(c)

    def err(d):
        ee = line(p["h"], p["er"] + d, s["w_seed_m"], p["t"], tand=p["tand"],
                  sigma=p["sigma"]).eeff
        return phase_error_deg(theta_deg, s["eeff"], ee) - limit_deg
    return float(brentq(err, 0.0, 0.5 * p["er"], xtol=1e-6))


def render_pointing(st: Stackup, cand: Stackup | None = None) -> str:
    """What the beamformer's permittivity uncertainty does to the beam, decision 0007."""
    from . import budget as b
    from .thresholds import THRESHOLDS, VARIANCE_FRACTION

    limit = THRESHOLDS[("s21_phase_diff_deg", "hfss_vs_ads")].value
    r = sensitivity(st, "beamformer")
    dk = r["one_at_a_time"]["rf_dielectric_permittivity"]
    x_dk = max(abs(dk["low"]["phase_error_deg"]["315"]),
               abs(dk["high"]["phase_error_deg"]["315"])) / LONGEST_STATE_DEG
    x_all = r["worst_corner_phase_error_deg"]["315"] / LONGEST_STATE_DEG
    floor = b.pointing_std_from_independent_phase_deg(b.quantisation_rms_deg(b.PHASE_BITS_DEFAULT))
    d_er = permittivity_for_phase_deg(st, "beamformer", limit)
    out = [f"Keeping the 315 degree state within {limit:g} degrees needs the beamformer "
           f"substrate permittivity known to plus or minus {d_er:.3f}, about "
           f"{d_er / st.construction('beamformer').er.value * 100:.1f} per cent.", "",
           "| Steering angle (deg) | Pointing budget (deg) | Shift, permittivity bound alone, "
           f"phase scaled by {x_dk * 100:.2f} per cent (deg) | Shift, worst corner, phase scaled "
           f"by {x_all * 100:.2f} per cent (deg) |",
           "| --- | --- | --- | --- |"]
    for a in b.STEERING_ANGLES_DEG:
        budget = math.sqrt(VARIANCE_FRACTION) * floor / math.cos(math.radians(a))
        out.append(f"| {a:g} | {budget:.3f} | {b.worst_proportional_pointing_deg(a, x_dk)[0]:.3f} | "
                   f"{b.worst_proportional_pointing_deg(a, x_all)[0]:.3f} |")
    out += ["", "Shift is the worst over the eight command origins, from "
            "`rfkit.budget.worst_proportional_pointing_deg`; the budget is decision 0007's "
            "pointing bound at that angle."]
    return "\n".join(out) + "\n"


SECTIONS = {
    "nominal": render_nominal, "tolerances": render_tolerances, "seeds": render_seeds,
    "sensitivity": render_sensitivity, "loss": render_loss, "patch": render_patch,
    "comparison": render_comparison, "sim001": render_sim001, "pointing": render_pointing,
}


def sync_text(text: str, st: Stackup, cand: Stackup | None) -> str:
    """Replace every generated block in ``text`` with a fresh rendering."""
    def repl(m):
        name = m.group(2)
        if name not in SECTIONS:
            raise StackupError(f"unknown generated block {name!r}")
        return m.group(1) + SECTIONS[name](st, cand) + m.group(4)
    return _BLOCK.sub(repl, text)


def check_docs(st: Stackup | None = None, cand: Stackup | None = None,
               write: bool = False) -> list[str]:
    """Documents whose generated blocks differ from the canonical file."""
    st = st or load()
    cand = cand or load_candidates()
    stale = []
    for rel in GENERATED_DOCS:
        path = REPO / rel
        text = path.read_text(encoding="utf-8")
        if not _BLOCK.search(text):
            stale.append(f"{rel}: no generated block")
            continue
        fresh = sync_text(text, st, cand)
        if fresh != text:
            stale.append(rel)
            if write:
                path.write_text(fresh, encoding="utf-8", newline="\n")
    return stale
